<?php
/**
 * @var $this Ip_Blogfeed_Block_Posts_List
 */
?>
<?php
    $_postCollection=$this->getPostCollection();
    $_helper = $this->helper('blogfeed');
?>
<div class="blogfeed-posts">
    <div class="pat"></div>
    <h1><span>Gallery</span></h1>
    <?php echo $this->getChildHtml('intro');?>
    <?php if(!$_postCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no posts matching the selection.') ?></p>
    <?php else: ?>
    <?php $_iterator = 0; ?>
        <ol class="post-list cycle-post" id="post-list">
            <?php foreach ($_postCollection as $_post): ?>
                <li id="<?php echo $this->getUrl('media') . $_post->getFeaturedImage(); ?>" class="post<?php if( ++$_iterator == sizeof($_postCollection) ): ?> last<?php endif; ?>">
                    <?php $_postNameStripped = $this->stripTags($_post->getTitle(), null, true); ?>
                    <div class="col2-set">
                        <div class="col-<?php echo $_iterator%2 ? 1 : 2?> gallery-image">
                            <a href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $_postNameStripped; ?>">
                                <img src="<?php echo $this->getUrl('media') . $_post->getFeaturedImage(); ?>" />
                            </a>
                        </div>
                        <div class="col-<?php echo $_iterator%2 ? 2 : 1?> gallery-content">
                            <h2 class="post-name">
                                <a href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $_postNameStripped; ?>">
                                    <?php echo $_post->getTitle(); ?>
                                </a>
                            </h2>
                            <p>
                                Posted on <?php echo $_helper->getTimestamp($_post);?>
                                <?php if($_post->isUpdated()):?>
                                    <span class="updated">(Last updated on <?php echo $_helper->getDate($_post);?>)</span>
                                <?php endif;?>
                            </p>
                            <div class="desc std">
                                <?php echo $_post->getShortDescription(); ?>
                                <a href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $_postNameStripped ?>" class="link-learn">
                                    <?php echo $this->__('Read More') ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>

        <div class="gallery-nav"></div>
        <script type="text/javascript">decorateList('post-list', 'none-recursive')</script>
    <?php endif; ?>
</div>
