<?php
/**
 * @var $this Ip_Popular_Block_Product_List
 */
?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="product-cycle" class="block-left">
    <div class="pat"></div>
    <h2><span>Popular Products</span></h2>
    <div class="mqt"></div>

    <div class="product-pager">
        <a href="#" class="prev">Previous</a>
        <a href="#" class="next">Next</a>
    </div>

    <div class="products">
        <?php foreach($_productCollection as $_product):?>
            <div class="product">
                <div class="pw">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <div class="product-img">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(180); ?>" width="180" height="180" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            <span class="button">View More</span>
                        </div>
                    </a>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>

                </div>
            </div><!--END product-->
        <?php endforeach;?>
    </div><!--END products-->

</div><!--END block-left-->
<?php endif;?>