<?php
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<div class="col2-set account-login">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-1 new-users">
        <div class="content">
            <h3><?php echo $this->__('Continue as a Guest') ?></h3>
            <?php echo $this->getChildHtml('register')?>
            <div class="buttons-set">
            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>

                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.continueAsGuest();"><span><span><?php echo $this->__('Continue as a Guest') ?></span></span></button>
            <?php else: ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
            <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-2 registered-users">
        <div class="content">
            <h3><?php echo $this->__('Registered Customers') ?></h3>
            <?php echo $this->getChildHtml('login')?>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <fieldset>
                    <ul class="form-list">
                        <li>
                            <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box">
                                <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                            </div>
                            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forgot-password"><?php echo $this->__('Forgot your password?') ?></a>
                        </li>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </ul>
                    <input name="context" type="hidden" value="checkout" />
                </fieldset>
            </form>
            <div class="buttons-set">
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
