<?php
/**
 * @var $this Mage_Core_Block_Template
 */
?>
<div class="page-bottom">
    <div class="container">
        <p class="alignleft">Copyright <?php echo date("Y"); ?>. FrogHopper. All rights reserved. <span><a href="<?php echo Mage::getUrl('sitemap');?>">Sitemap</a>. <a href="<?php echo Mage::getUrl('terms');?>">Conditions of Sale</a></span></p><!-- 
        <p class="alignright"><a href="http://www.inverseparadox.com" target="_blank">Website Produced</a> by: Inverse Paradox</p> -->
    </div><!--END container-->
</div><!--END page-bottom-->

<div class="social-wrap">
    <div class="social">
        <?php echo $this->getChildHtml('social_media'); ?>
    </div>
</div>